### ISSUE TITLE
Публикация: Добавление нескольких страниц сразу

### ISSUE THREAD

**Issue by mr9d** [mr9d/acomics-public#12]
Должна быть возможность выбора сразу нескольких файлов с компьютера. После выбора - можно добавить названия и описания для каждой страницы в отдельности.

**Comment by SickRogue** [comment]
Пример как это реализовано на Охманге:
(все на одной странице)

![изображение](https://user-images.githubusercontent.com/117465947/202260660-5756f430-5edd-471d-89fb-3d62101ee458.png)
![изображение](https://user-images.githubusercontent.com/117465947/202260677-d57c742a-eeee-4e73-8937-d4f727ab6f08.png)

Страницы можно перемещать, зажав курсором

**Comment by darth-biomech** [comment]
Возможно это подходит сюда, но было бы ещё неплохо иметь возможность массовой замены уже опубликованных страниц комикса.

**Comment by geekyreverie** [comment]
Очень хочется, чтобы можно было переносить страницы Drag and Drop'ом, особенно когда их много.

**Comment by mr9d** [comment]
Сделали https://github.com/Xpamoff/acomics-upload-module

Новость: https://vk.com/acomics?w=wall-19453433_18325
