### ISSUE TITLE
Публикация: Автоматическое сжатие страниц при загрузке

### ISSUE THREAD

**Issue by mr9d** [mr9d/acomics-public#13]
У автора должна быть возможность включить или выключить автоматическое сжатие страниц при загрузке на сайт. Как вариант, сжимать все страницы, превышающие лимит сайта.

**Comment by AlexDsche** [comment]
Если будет отключаемым – отлично, но нужно хорошо протестировать: у нас есть адского размера PNG с прозрачностью (Ава и демон), есть анимированные gif и т.п.
