### ISSUE TITLE
Регистрация: Ошибочное перенаправление после подтверждения почты

### ISSUE THREAD

**Issue by mr9d** [mr9d/acomics-public#21]
После подтверждения регистрации по ссылке, которая приходит на почту, пользователь вводит в появившейся форме имя пользователя и пароль, и система оставляет его на той же странице, только теперь с сообщением об ошибке : «Эта страница только для неавторизованных пользователей».

**Comment by lizabook** [comment]
Баг не воспроизводится в браузерах: Opera, Google Chrome, Microsoft Edge, Yandex.
Воспроизводится только в ситуации, если:
1. Зарегистрироваться
2. Получить письмо со ссылкой для подтверждения регистрации
3. Перейти по ссылке
4. Авторизоваться (после авторизации автоматически осуществляется переход на главную страницу сайта)
5. Ещё раз попытаться перейти по ссылке из письма
Возможно, было исправлено?

**Comment by mr9d** [comment]
@lizabook спасибо! Я думаю, тогда баг можно закрывать?
