### ISSUE TITLE
Настройки: POSTится не та кнопка формы в Яндекс.Браузере

### ISSUE THREAD

**Issue by mr9d** [mr9d/acomics-public#5]
Я.Браузер Зайти на страницу http://acomics.ru/settings/security Нажать кнопку "сменить емейл" Отправится submit=changePass, как будто была нажата первая "сменить пароль".

Но на http://acomics.ru/settings/profile, например, кнопки работают нормально и отправляется правильная. Поэтому непонятно, что вызывает баг на странице настроек безопасности.

**Баг от 2015 года. Нужно проверить актуальность.**

**Comment by lizabook** [comment]
Неактуально.
Нажатие "Сменить email" отправляет submit: changeEmail.
На всякий случай проверила ещё дополнительно через Chrome, Edge, Opera - тоже везде отправляется правильно.
Другой вопрос (возможно, спровоцирует создание нового бага): почему при отправке формы передаются все данные, которые были на странице (включая старый пароль, если у браузера включено автозаполнение паролей)?
Возможно, стоит отделить форму смены пароля от формы смены емэйла?
