### ISSUE TITLE
Добавить возможность обрезать загруженные аватарки/баннеры через интерфейс сайта + авторесайзинг

### ISSUE THREAD

**Issue by bubenchikus** [mr9d/acomics-public#53]
Объясню предложение на примере аватарок юзеров.

Сейчас от пользователя требуется загружать аватарки 100х100 px. Если формат загруженной картинки не соответствует требованию, возвращается страница с ошибкой. С точки зрения юзера будет гораздо удобнее, если работа по форматированию картинки будет частично переложена с него на сервис. Как это может выглядеть?

1) Пользователь загружает картинку произвольного размера, чтобы поставить ее на аватарку.
2) Всплывает окно, в котором предлагается выделить область, по которой будет произведена обрезка картинки. Соотношение сторон области фиксированное (в случае с аватарками это 1). По дефолту некоторая область уже выделена, так что если пользователь поленится и просто нажмет ОК, процесс не развалится.
3) Сервис сохраняет обрезанную картинку с правильными пропорциями, после чего ресайзит её до нужных 100х100 px.

Дополнительно:
1) Нужно выставить верхнюю границу для веса загружаемого файла, чтобы не перегружать сервер.
2) Можно выставить нижнюю границу для разрешения загружаемого файла, чтобы запретить пользователю грузить совсем мыльное мыло. По этой же причине в окне обрезки можно ограничить минимальный размер выделенной области.
3) Помним про необходимость автоматически подтирать загруженные/промежуточные картинки, особенно если в процессе что-то идёт не так и пользователь будет пытаться грузить и обрезать файлы ещё раз.

Для референса можно посмотреть на процесс загрузки аватарки и выбора миниатюры в ВК или процесс загрузки обложки проекта на Artstation.

**Comment by bubenchikus** [comment]
Текущие требования к форматам аватарок, баннеров и т.д. стоит оставить в качестве рекомендаций для юзеров/художников, которые хотят создавать их специально под acomics. Для остальных же понизится порог входа и сложность работы с сайтом %)

**Comment by mr9d** [comment]
Авторесайзинг заработал для выпусков, для шапки и частично для баннеров.

**Comment by mr9d** [comment]
Возможность обрезки картинок заработала для аватарок. Дальнейшие обсуждения и доработки будут вестись в репозитории: https://github.com/mr9d/acomics-crop
