### ISSUE TITLE
Комментарии: Изменить цвет уведомления автора о новых комментариях

### ISSUE THREAD

**Issue by Mikhail140780** [mr9d/acomics-public#55]
Некоторые авторы нервно реагируют на кроваво-красный цвет уведомления о наличии новых комментариев.
[Например](https://vk.com/monoxromik?w=wall-100004546_7690_r7706)

Предлагаю сменить цвет на столь же яркий, но не ассоциирующийся с чем-то плохим - например, оранжевый.

**Comment by mr9d** [comment]
Сменил на зеленый.
