### ISSUE TITLE
Письма. Отправлять оповещения о новых выпусках.

### ISSUE THREAD

**Issue by Aristarhys** [mr9d/acomics-public#60]
Сейчас есть возможность подписаться на rss рассылку для комикса и таким образом отслеживать новые выпуски. Но раз портал уже умеет отправлять сервисные письма (например при восстановлении пароля) - было бы неплохо рассылать письма раз в неделю с новыми выпусками.

Из минусов - должна быть система "отписаться", есть возможность попадание писем в спам и весь ворох проблем массовых рассылок емейлов.

**Comment by mr9d** [comment]
@Aristarhys привет! Закрываю задачу как дубликат https://github.com/mr9d/acomics-public/issues/15
