### ISSUE TITLE
Проверить что куки авторизации http only

### ISSUE THREAD

**Issue by Aristarhys** [mr9d/acomics-public#67]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

Таким образом при XSS атаке (например если кто-то умудриться как то вставить скрипт в комментарий или в какое то описание), ничего важного (как авторизация) не утечет

**Comment by mr9d** [comment]
Проверил, добавил httpOnly для PHPSESSID. Спасибо за внимательность и сознательность!
