### ISSUE TITLE
Увеличить допустимое разрешение и вес баннеров к комиксам

### ISSUE THREAD

**Issue by UsagiChao** [mr9d/acomics-public#69]
Размер файла увеличить до хотя бы 1 Мб, размер изображения увеличить минимум в 3 раза

**Comment by mr9d** [comment]
Актуально для современных дисплеев с повышенной плотностью пикселов.

**Comment by mr9d** [comment]
@UsagiChao Пока закрою, так как появился автоматический ресайз при загрузке картинок. Если проблема осталась актуальной - дайте знать.
